Names
Specifying a name for an/any object now requires a name="str" keyword argument in most cases.

Unexpected keyword arguments are reported as TypeErrors in most cases.

Numerous documentation and some test updates.